version: '3.9'
services:
  minio:
    image: minio/minio:RELEASE.2022-03-11T23-57-45Z.fips
    command: ["server", "--console-address", ":9001", "/data"]
    environment:
      MINIO_ROOT_USER: ROOT
      MINIO_ROOT_PASSWORD: PASSWORD
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - $PWD/data:/data
  redis:
    image: redislabs/redisearch:2.4.2
    ports: 
      - 6379:6379
    volumes:
      - $PWD/db:/data
  tika:
    image: apache/tika:1.21
    ports:
      - 9998:9998
